### ISSUE TITLE
MIRAI Summer 2019 overview

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/MIRAI#1]
Create basic webpage for the MIRAI project:
- [x] Grab information from grant application PDF (ask @vigliensoni)
- [x] Use same template as SIMSSA, without the blog. 
- [x] Technologies: Jekyll (ask @evansavage)
- [x] Serve the site using Github pages
- [x] Determine URL (mirai.simssa.ca or we need a new domain?) and set up DNS (ask @vigliensoni)
- [x] Website should be fully bilingual

**Comment by vigliensoni** [comment]
Create basic webpage for the MIRAI project:
- [ ] Grab information from grant application PDF (ask @vigliensoni)
- [ ] Use same template as SIMSSA, without the blog. 
- [ ] Technologies: Jekyll (ask @evansavage)
- [ ] Serve the site using Github pages
- [ ] Determine URL (mirai.simssa.ca or we need a new domain?) and set up DNS (ask @vigliensoni)
- [ ] Website should be fully bilingual

**Comment by fujinaga** [comment]
As for the URL, we can use: http://ddmal.music.mcgill.ca/mirai
