### ISSUE TITLE
Change images under navigation bar.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/MIRAI#3]
Change all images under the navigation bar for each tab (i.e., home, about, participants, impact, contact us)

We should only use Public Domain images. The themes should be future, music, information, etc. You can try to find something on [unsplash](https://unsplash.com). 

Examples of images we could use are:

https://unsplash.com/photos/1-mh6U3qeGQ
https://unsplash.com/photos/kBUfvkbFIoE
https://unsplash.com/photos/466ENaLuhLY

**Comment by fujinaga** [comment]
Can we use the second image for the home page?
You can crop it to be narrower.

**Comment by evansavage** [comment]
Changed it, let me know what you think!

**Comment by fujinaga** [comment]
Looking good!
Thank you.
