### ISSUE TITLE
Incorporate presentations and publications.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/MIRAI#5]
Use the same ones we have for SIMSSA.

**Comment by emilyhopkins** [comment]
FYI the SIMSSA page is quite out of date at the moment. Hoping to fix soon but in mean time let me know if you want and I can export whatever file types you want (HTML, bib, etc) from the updated Zotero library

**Comment by evansavage** [comment]
HTML of the most recent exports would be really helpful for both sites!

**Comment by evansavage** [comment]
These should be now updated, let me know what you think!

**Comment by fujinaga** [comment]
Looks great.
Thank you.
